// The multiplication table uses row ∘ col, with identities in positions 0..objects-1.
function homSets(table, objects) {
  const n = table.length
  return table.map((_, morphism) => {
    let source = -1
    let target = -1
    for (let object = 0; object < objects; object += 1) {
      if (table[morphism][object] === morphism) source = object
      if (table[object][morphism] === morphism) target = object
    }
    if (source < 0 || target < 0) throw new Error('The category table has a morphism without endpoints.')
    return `${source}:${target}`
  })
}

function canonicalPartition(parent) {
  const labels = new Map()
  return parent.map(root => {
    while (parent[root] !== root) root = parent[root]
    if (!labels.has(root)) labels.set(root, labels.size)
    return labels.get(root)
  })
}

function principalCongruence(table, left, right) {
  const n = table.length
  const parent = Array.from({ length: n }, (_, index) => index)
  const find = index => {
    while (parent[index] !== index) index = parent[index] = parent[parent[index]]
    return index
  }
  const join = (a, b) => {
    a = find(a)
    b = find(b)
    if (a === b) return false
    parent[b] = a
    return true
  }
  join(left, right)
  let changed = true
  while (changed) {
    changed = false
    for (let a = 0; a < n; a += 1) {
      for (let b = a + 1; b < n; b += 1) {
        if (find(a) !== find(b)) continue
        for (let c = 0; c < n; c += 1) {
          const afterA = table[c][a]
          const afterB = table[c][b]
          const beforeA = table[a][c]
          const beforeB = table[b][c]
          if (afterA < n && afterB < n && join(afterA, afterB)) changed = true
          if (beforeA < n && beforeB < n && join(beforeA, beforeB)) changed = true
        }
      }
    }
  }
  return canonicalPartition(parent)
}

// Joins of congruences need only equivalence closure: composition preserves
// every link in a chain, so it also preserves the chain's transitive closure.
function joinPartitions(left, right) {
  const n = left.length
  const parent = Array.from({ length: n }, (_, index) => index)
  const representative = (labels, value) => labels.indexOf(value)
  const find = index => {
    while (parent[index] !== index) index = parent[index] = parent[parent[index]]
    return index
  }
  for (let index = 0; index < n; index += 1) {
    parent[find(index)] = find(representative(left, left[index]))
    parent[find(index)] = find(representative(right, right[index]))
  }
  return canonicalPartition(parent)
}

function refines(left, right) {
  const classImages = []
  for (let index = 0; index < left.length; index += 1) {
    const sourceClass = left[index]
    if (classImages[sourceClass] === undefined) classImages[sourceClass] = right[index]
    else if (classImages[sourceClass] !== right[index]) return false
  }
  return true
}

function countBits(mask) {
  let count = 0
  while (mask) {
    mask &= mask - 1
    count += 1
  }
  return count
}

function generatedPoset(elements, generators, join, rank, lessOrEqual, key) {
  elements.sort((a, b) => rank(a) - rank(b) || key(a).localeCompare(key(b)))
  const nodes = elements.map((value, id) => ({ id, value, rank: rank(value) }))
  const indexOf = new Map(nodes.map(node => [key(node.value), node.id]))
  const covers = []
  for (let lower = 0; lower < nodes.length; lower += 1) {
    // Every cover is obtained by adjoining one generator: if a larger element
    // is generated by several, at least one of them starts a path upward.
    const candidates = [...new Set(generators.map(generator =>
      indexOf.get(key(join(nodes[lower].value, generator)))))]
      .filter(upper => upper !== lower)
      .sort((a, b) => nodes[a].rank - nodes[b].rank || a - b)
    const immediate = []
    for (const upper of candidates) {
      if (immediate.some(middle => lessOrEqual(nodes[middle].value, nodes[upper].value))) continue
      immediate.push(upper)
      covers.push([lower, upper])
    }
  }
  return { nodes, covers }
}

export function congruencePoset(table, objects) {
  const n = table.length
  const hom = homSets(table, objects)
  const generators = []
  const generatorKeys = new Set()
  for (let left = 0; left < n; left += 1) {
    for (let right = left + 1; right < n; right += 1) {
      if (hom[left] !== hom[right]) continue
      const partition = principalCongruence(table, left, right)
      const key = partition.join(',')
      if (!generatorKeys.has(key)) {
        generators.push(partition)
        generatorKeys.add(key)
      }
    }
  }
  const discrete = Array.from({ length: n }, (_, index) => index)
  const elements = [discrete]
  const seen = new Set([discrete.join(',')])
  for (let index = 0; index < elements.length; index += 1) {
    for (const generator of generators) {
      const next = joinPartitions(elements[index], generator)
      const key = next.join(',')
      if (seen.has(key)) continue
      seen.add(key)
      elements.push(next)
    }
  }
  return generatedPoset(elements, generators, joinPartitions,
    partition => n - new Set(partition).size, refines, partition => partition.join(','))
}

export function idealPoset(table) {
  const n = table.length
  if (n > 30) throw new Error('Ideal display supports categories with at most 30 morphisms.')
  const principal = Array.from({ length: n }, (_, seed) => {
    let mask = 1 << seed
    const queue = [seed]
    for (let index = 0; index < queue.length; index += 1) {
      const morphism = queue[index]
      for (let other = 0; other < n; other += 1) {
        for (const composite of [table[morphism][other], table[other][morphism]]) {
          if (composite >= n || (mask & (1 << composite))) continue
          mask |= 1 << composite
          queue.push(composite)
        }
      }
    }
    return mask
  })
  const elements = [0]
  const seen = new Set(elements)
  for (let index = 0; index < elements.length; index += 1) {
    for (const generator of principal) {
      const next = elements[index] | generator
      if (seen.has(next)) continue
      seen.add(next)
      elements.push(next)
    }
  }
  return generatedPoset(elements, principal, (left, right) => left | right,
    countBits, (left, right) => (left & right) === left, String)
}
