import {
  categoryLabel,
  findCell,
  getCategoryMetadata,
  getManifest,
  getPropositions,
  loadCategory,
} from '../data.js'
import { escapeHtml, iconText, setTitle } from '../ui.js'
import { mountCategoryVisualization } from '../visualization.js'
import { congruencePoset, idealPoset } from '../posets.js'
import { mountPoset } from '../poset-view.js'
import { categoryCenter, categoryTrace } from '../category-algebra.js'
import categoryTemplate from './category.html'

function renderMatrix(table, morphisms) {
  if (morphisms === 0) return '<p>The empty category has no morphisms or multiplication table.</p>'
  return `<div class="table-wrap"><table class="matrix"><tbody>
    <tr><th><i>row</i> ∘ <i>col</i></th>${Array.from({ length: morphisms }, (_, index) => `<th>${index}</th>`).join('')}</tr>
    ${table.map((row, rowIndex) => `<tr><th>${rowIndex}</th>${row.map(value => `<td>${value < morphisms ? value : '<span class="undefined">/</span>'}</td>`).join('')}</tr>`).join('')}
  </tbody></table></div>`
}

// Every proposition is known for every category, so there is no longer an
// "unknown" case to render.
function renderCategoryFacts(propositions, mask) {
  return `<div class="fact-list">
    ${propositions.map(proposition => {
      const value = (mask & (2 ** proposition.bit)) !== 0
      return `<a class="tag is-${value ? 'success' : 'danger'}" href="/proposition/${encodeURIComponent(proposition.name)}" data-link aria-label="${escapeHtml(proposition.name)}: ${value ? 'true' : 'false'}">${iconText(value ? 'check' : 'xmark', escapeHtml(proposition.name))}</a>`
    }).join('')}
  </div>`
}

function setText(app, selector, value) {
  app.querySelector(selector).textContent = value
}

function mountCenter(element, { elements, multiplication }, viewer) {
  const hasObjects = elements[0].length > 0
  element.innerHTML = `<p class="help">Z(C) = Nat(Id<sub>C</sub>, Id<sub>C</sub>). ${elements.length} ${elements.length === 1 ? 'element' : 'elements'}. ${hasObjects ? 'Components are listed in object order. Select an element to highlight them.' : 'The empty tuple is its sole element.'}</p>
    <div class="table-wrap"><table class="table is-striped is-fullwidth"><thead><tr><th>Element</th><th>Components</th></tr></thead><tbody>
      ${elements.map((components, id) => `<tr><td>${hasObjects ? `<button class="button is-small is-light" type="button" data-center-element="${id}">Z${id}</button>` : `Z${id}`}</td><td>(${components.join(', ')})</td></tr>`).join('')}
    </tbody></table></div>
    <p class="help">Composition (row ∘ column):</p>
    <div class="table-wrap"><table class="matrix"><tbody><tr><th>∘</th>${elements.map((_, id) => `<th>Z${id}</th>`).join('')}</tr>
      ${multiplication.map((row, id) => `<tr><th>Z${id}</th>${row.map(product => `<td>Z${product}</td>`).join('')}</tr>`).join('')}
    </tbody></table></div>`
  element.addEventListener('click', event => {
    const button = event.target.closest('[data-center-element]')
    if (!button || !element.contains(button)) return
    const id = Number(button.dataset.centerElement)
    viewer.highlight({ kind: 'center', id, value: elements[id] })
  })
}

function mountTrace(element, classes, viewer) {
  element.innerHTML = `<p class="help">Tr(C) is the set of endomorphisms modulo the equivalence relation generated by f ∘ g ~ g ∘ f. ${classes.length} ${classes.length === 1 ? 'class' : 'classes'}.${classes.length ? ' Select a class to highlight its morphisms.' : ''}</p>
    ${classes.length ? `<div class="table-wrap"><table class="table is-striped is-fullwidth"><thead><tr><th>Class</th><th>Endomorphisms</th></tr></thead><tbody>
      ${classes.map((members, id) => `<tr><td><button class="button is-small is-light" type="button" data-trace-class="${id}">T${id}</button></td><td>{${members.join(', ')}}</td></tr>`).join('')}
    </tbody></table></div>` : '<p>∅</p>'}`
  element.addEventListener('click', event => {
    const button = event.target.closest('[data-trace-class]')
    if (!button || !element.contains(button)) return
    const id = Number(button.dataset.traceClass)
    viewer.highlight({ kind: 'trace', id, value: classes[id] })
  })
}

export async function renderCategoryPage({ app, morphisms, objects, index, isCurrent }) {
  const manifest = await getManifest()
  const cell = findCell(manifest, morphisms, objects)
  if (!cell || index < 0 || index >= cell.count) return { found: false, cleanup: () => {} }

  const [category, metadata, propositions] = await Promise.all([
    loadCategory(cell, index),
    getCategoryMetadata(cell, index),
    getPropositions(),
  ])
  if (!isCurrent()) return { found: true, stale: true, cleanup: () => {} }

  const { table, mask } = category
  const label = categoryLabel(morphisms, objects, index)
  setTitle(label)
  app.innerHTML = categoryTemplate
  setText(app, '[data-category-title]', label)
  setText(app, '[data-category-label]', label)
  setText(app, '[data-category-morphisms]', morphisms)
  setText(app, '[data-category-objects]', objects)
  setText(app, '[data-category-index]', index)

  const name = app.querySelector('[data-category-name]')
  name.textContent = metadata?.friendlyName || 'N/A'
  name.classList.toggle('muted', !metadata?.friendlyName)
  const description = app.querySelector('[data-category-description]')
  description.textContent = metadata?.description || 'N/A'
  description.classList.toggle('muted', !metadata?.description)

  const visualization = app.querySelector('[data-category-visualization]')
  visualization.innerHTML = morphisms > 0
    ? `<div class="box viz-box">
        <div class="viz-toolbar"><span class="help">Drag the objects to rearrange the quiver.</span><button class="button is-small is-light" type="button" data-reset-viz>${iconText('rotate-left', 'Reset layout')}</button></div>
        <div class="viz" id="category-viz"></div>
        <div class="viz-highlight" data-viz-highlight hidden>
          <div class="viz-toolbar"><span data-viz-highlight-status role="status" aria-live="polite"></span><button class="button is-small is-light" type="button" data-clear-highlight>Clear highlight</button></div>
          <div class="viz-legend" data-viz-legend></div>
        </div>
      </div><p class="help">Morphisms 0 through ${objects - 1} are identities, shown as objects.</p>`
    : '<p>The empty category has no quiver.</p>'
  app.querySelector('[data-category-table]').innerHTML = `${renderMatrix(table, morphisms)}${morphisms > 0 ? '<p class="help">“/” indicates an undefined composition.</p>' : ''}`
  app.querySelector('[data-category-facts]').innerHTML = renderCategoryFacts(propositions, mask)
  const categoryViewer = mountCategoryVisualization(app.querySelector('#category-viz'), table, objects, morphisms)

  for (const [selector, calculate, kind] of [
    ['[data-category-congruences]', () => congruencePoset(table, objects), 'congruence'],
    ['[data-category-ideals]', () => idealPoset(table), 'ideal'],
  ]) {
    setTimeout(() => {
      if (!isCurrent()) return
      const target = app.querySelector(selector)
      try {
        const poset = calculate()
        if (isCurrent()) mountPoset(target, poset, {
          kind, morphisms,
          onSelect: selection => categoryViewer.highlight(selection),
        })
      } catch (error) {
        if (isCurrent()) target.innerHTML = `<div class="notification is-danger is-light">${escapeHtml(error.message || error)}</div>`
      }
    }, 0)
  }

  for (const [selector, calculate, mount] of [
    ['[data-category-center]', () => categoryCenter(table, objects), mountCenter],
    ['[data-category-trace]', () => categoryTrace(table, objects), mountTrace],
  ]) {
    setTimeout(() => {
      if (!isCurrent()) return
      const target = app.querySelector(selector)
      try {
        const result = calculate()
        if (isCurrent()) mount(target, result, categoryViewer)
      } catch (error) {
        if (isCurrent()) target.innerHTML = `<div class="notification is-danger is-light">${escapeHtml(error.message || error)}</div>`
      }
    }, 0)
  }

  return {
    found: true,
    cleanup: categoryViewer.cleanup,
  }
}
